#  Category.create en: 'noun',         de: 'Nomen',        ru: 'существительное'
#  Category.create en: 'adjective',    de: 'Adjektiv',     ru: 'прилагательное'
#  Category.create en: 'verb',         de: 'Verb',         ru: 'глагол'
#  Category.create en: 'pronoun',      de: 'Pronomen',     ru: 'местоимение'
#  Category.create en: 'numeral',      de: 'Numerale',     ru: 'числительное'
#  Category.create en: 'adverb',       de: 'Adverb',       ru: 'наречие'
#  Category.create en: 'article',      de: 'Artikel',      ru: 'артикль'
#  Category.create en: 'pretext',      de: 'Präposition',  ru: 'предлог'
#  Category.create en: 'union',        de: 'Konjuktion',   ru: 'союз'
#  Category.create en: 'particle',     de: 'Partikel',     ru: 'частица'
#  Category.create en: 'interjection', de: 'Interjektion', ru: 'междометие'
#  Category.create en: 'expression',   de: 'Ausdruck',     ru: 'выражение'
#  Category.create en: 'personal pronoun', de: 'Personalpronomen', ru: 'личное местоимение'

  pos = 'Nomen'
Entry.create pos: pos, art: 'das', de: 'Alter',    pl: 'Alter',       en: 'age',        ru: 'возраст'
Entry.create pos: pos, art: 'der', de: 'Beruf',    pl: 'Berufe',      en: 'profession', ru: 'профессия'
Entry.create pos: pos, art: 'das', de: 'Beispiel', pl: 'Beispiele',   en: 'example',    ru: 'пример'
Entry.create pos: pos, art: 'das', de: 'Verb',     pl: 'Verben',      en: 'verb',       ru: 'глагол'
Entry.create pos: pos, art: 'das', de: 'Nomen',    pl: 'Nomen',       en: 'noun',       ru: 'существительное'
Entry.create pos: pos, art: 'das', de: 'Auto',     pl: 'Autos',       en: 'car',        ru: 'автомобиль'
Entry.create pos: pos, art: 'das', de: 'Foto',     pl: 'Fotos',       en: 'photo',      ru: 'фотография'
Entry.create pos: pos, art: 'der', de: 'Stuhle',   pl: 'Stühle',      en: 'chair',      ru: 'стул'
Entry.create pos: pos, art: 'die', de: 'Lampe',    pl: 'Lampen',      en: 'lamp',       ru: 'лампа'
Entry.create pos: pos, art: 'das', de: 'Haus',     pl: 'die Häuser',  en: 'house',      ru: 'дом'
Entry.create pos: pos, art: 'der', de: 'Tisch',    pl: 'Tische',      en: 'table',      ru: 'стол'

pos = 'Personalpronoun'
Entry.create pos: pos, de: 'ich', en: 'I',    ru: 'я',  trxn: 'iç'
Entry.create pos: pos, de: 'du',  en: 'you',  ru: 'ты', trxn: 'du:'
Entry.create pos: pos, de: 'Sie', en: 'You',  ru: 'Вы', trxn: 'zi:'
Entry.create pos: pos, de: 'er',  en: 'he',   ru: 'он'
Entry.create pos: pos, de: 'sie', en: 'she',  ru: 'она'
Entry.create pos: pos, de: 'es',  en: 'it',   ru: 'оно'
Entry.create pos: pos, de: 'wir', en: 'we',   ru: 'мы'
Entry.create pos: pos, de: 'ihr', en: 'you',  ru: 'вы'
Entry.create pos: pos, de: 'sie', en: 'they', ru: 'они'

pos = 'Verb'
Entry.create pos: pos, de: 'arbeiten',       en: 'work',        ru: 'работать'
Entry.create pos: pos, de: 'haben',          en: 'have',        ru: 'иметь'
Entry.create pos: pos, de: 'sein',           en: 'be',          ru: 'быть'
Entry.create pos: pos, de: 'wohnen',         en: 'reside',      ru: 'проживать'
Entry.create pos: pos, de: 'heißen',         en: 'be called',   ru: 'зваться'
Entry.create pos: pos, de: 'buchstabieren',  en: 'spell',       ru: 'произносить по буквам'
Entry.create pos: pos, de: 'müchten',        en: 'would like',  ru: 'хотеть бы'
Entry.create pos: pos, de: 'leben',          en: 'live',        ru: 'жить'
Entry.create pos: pos, de: 'sprechen',       en: 'speak',       ru: 'говорить'
Entry.create pos: pos, de: 'studieren',      en: 'study',       ru: 'учиться (в ВУЗе)'
Entry.create pos: pos, de: 'warten',         en: 'wait',        ru: 'ждать, ожидать'
Entry.create pos: pos, de: 'werden',         en: 'become',      ru: 'становиться'
Entry.create pos: pos, de: 'lernen',         en: 'learn',       ru: 'учить, учиться'
Entry.create pos: pos, de: 'entschuldigen',  en: 'apologize',   ru: 'извинять'
Entry.create pos: pos, de: 'antworten',      en: 'reply',       ru: 'отвечать'
Entry.create pos: pos, de: 'bieten',         en: 'ask',         ru: 'спрашивать'
Entry.create pos: pos, de: 'fahren',         en: 'drive',       ru: 'ехать'
Entry.create pos: pos, de: 'funktionieren',  en: 'function',    ru: 'работать'
Entry.create pos: pos, de: 'können',         en: 'can',         ru: 'мочь, быть в состоянии'
